# https://starship.rs/config
"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$character"""
right_format = """$all"""

[aws]
disabled = true

[bun]
format = '[$symbol($version )]($style)'

[cmake]
format = '[$symbol($version )]($style)'

[conda]
format = '[$symbol$environment]($style) '

[deno]
format = '[$symbol($version )]($style)'

[docker_context]
format = '[$symbol$context]($style) '

[dotnet]
format = '[$symbol($version )(🎯 $tfm )]($style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[golang]
format = '[$symbol($version )]($style)'

[nix_shell]
format = '[$symbol$state( \($name\))]($style) '

[nodejs]
format = '[$symbol($version )]($style)'

[package]
format = '[$symbol$version]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
format = '[$symbol($version )]($style)'

[zig]
format = '[$symbol($version )]($style)'
